### ISSUE TITLE
add scss file that enables complete components

### ISSUE THREAD

**Issue by graste** [graste/inuit-complete#3]
Create a `_inuit-custom.scss` file that looks like this:

``` scss
// to enable all modifiers:
$inuit-enable-everything:           true !default;
// or only enable all modifiers of specific inuit objects/trumps:
$inuit-enable-block:                false !default;
$inuit-enable-box:                  false !default;
$inuit-enable-buttons:              false !default;
$inuit-enable-flag:                 false !default;
$inuit-enable-layout:               false !default;
$inuit-enable-list-block:           false !default;
$inuit-enable-list-inline:          false !default;
$inuit-enable-list-ui:              false !default;
$inuit-enable-media:                false !default;
$inuit-enable-pack:                 false !default;
$inuit-enable-table:                false !default;
$inuit-enable-spacing:              false !default;
$inuit-enable-spacing-responsive:   false !default;

…
…
…
@if (($inuit-enable-everything == true) or ($inuit-enable-buttons == true)) {
    $inuit-enable-btn--small: true !global !default;
    $inuit-enable-btn--large: true !global !default;
    $inuit-enable-btn--full:  true !global !default;
    $inuit-enable-btn--pill:  true !global !default;
}
@import "inuit/objects.buttons";

…
…
…
```

This pattern would enable to get whole parts of inuit without deciding exactly what modifiers one wants. May be a nice shortcut in small projects where one knows what general parts of inuit are wanted.
